### PR TITLE
Update Prerequisites and Sample Command

### PR DESCRIPTION
**Pull request by thepaulmacca**
Just a quick PR to update the Azure CLI extension name, and add a step in the prereqs to register some additional resource providers that I was missing (and others may be missing too)

### CODE REVIEW

**Comment by PixelRobots** [comment]
Just seen this. Did you mean to close?

**Comment by thepaulmacca** [comment]
I was just going through my PRs and noticed this one has been open for a while, and was unsure if you wanted to do anything with it or not?

**Comment by PixelRobots** [comment]
Awesome. Will do some testing and then merge in.

**Comment by thepaulmacca** [comment]
Cool thanks! 👍

**Comment by JoeyC-Dev** [comment]
@PixelRobots @thepaulmacca 
Both `az k8s-configuration` and `az k8sconfiguration` have been deprecated now. Should use `az k8s-configuration flux` instead.

**Pull request closed without merging**
